# Configuration settings for the Silo Pool Service. On start up,
# the service will first look for a filename using the environment
# variable SILOPOOL_CONFIG_FILE, then will look in the install
# directory (where app.rb is) for a file named 'config.yml'.

# Please avoid the use of TABs in this file.

# Should we log database queries? defaults to false.  These generate
# very large logs, so it's only recommended for troubleshooting, or,
# you know, hacking around.

log_database_queries:        false

# If set, direct log information to this syslog facility (see
# /etc/syslog.conf), otherwise log to STDERR.

# log_syslog_facility:       

# Database connection string, formatted as  
#
#   vendor://username:password@hostname:port/database" 
#
# Supported vendors: postgres. Some fields are optional - for
# instance, if there is no password and you use the default port,
# 5432: 
#
# "vendor://username@hostname/database"
#
# N.B.  This means that this config file should have read permissions
# retricted to the user running the service, or an appropriately
# restricted group.

database_connection_string:  postgres://daitss:topsecret@example.org/store_master

# What hostname are we running the service under?  This is used as a tag in the logs. Defaults
# to the hostname of the server

virtual_hostname:            silo-pool.example.org

# Where should temporary files be created? This should be at least twice the size of the
# largest package you plan to ingest, plus headroom. 

temp_directory:           /var/tmp/

# For installations that are using tivoli as a silo backing store, this
# determines the tivoli server name

# tivoli_server: YourTivoliServer

# When we retrieve silo data from the tivoli tapes, we cache it here:

# silo_temp_directory:     /var/tmp/

# If we do fixity checks, we have two notions: when should packages in
# a particular silo have to be re-checked (they are stale) and when
# they have they become critically out-dated (expired).  Here we set the
# time in days for these two values. If they are not set, then we
# won't report them on the silo information page.

# fixity_stale_days: 45
# fixity_expired_days: 60
