# This is an example of the DAITSS configuration file restricted to
# the data necessary to run the silo-pool service.
#
# You must set up your web server to set the environment variable
# DAITSS_CONFIG to point to a configuration file along these lines,
# though typically it will have sections for many services in addition
# to this one.
#
# Please don't use tabs in this file.

defaults:
     fixity_expired_days:        60
     fixity_stale_days:          45

database:
     silo_db:                    postgres://silos:topsecret@localhost/my_silo_db

# We normally name sections after the virtual hostname used by an
# web server (this is so one physical host can run multiple services
# of the same kind).  An application's configuration code typically
# checks the VIRTUAL_HOSTNAME environment variable to determine the
# appropriate section to load.  Usually VIRTUAL_HOSTNAME is set in
# the same place that the DAITSS_CONFIG environment is set.

silo-pool.example.org:
     log_database_queries:       false
     log_syslog_facility:        LOG_LOCAL0
     log_filename:               /path/to/name/of/file.log
     silo_temp_directory:        /tmp
     tivoli_server:              TIVOLI
     fixity_expired_days:        60
     fixity_stale_days:          30

disk-fixity:
     hostname:                   silo-pool.example.org
     pid_directory:              /var/run/fixity
     log_syslog_facility:        LOG_LOCAL2   
     log_filename:               /path/to/disk-fixity.com
     fresh_enough:               7
     log_database_queries:       false

tape-fixity:
     fixity_disk:                /path/to/large/filesystem/
     fresh_enough:               0
     hostname:                   silo-pool.example.org
     log_database_queries:       false
     log_filename:               /path/to/tape-fixity.com
     log_syslog_facility:        LOG_LOCAL2   
     pid_directory:              /var/run/fixity
     silo_user:                  silo
     tivoli_server:              TIVOLI
     

# defaults
# ========
#
# default:fixity_expired_days
# ---------------------------
# The number of days after which fixity check data will
# be reported as out-of-date.  Defaults to 60 days. Used
# by some of the fixity scripts
#
# default:fixity_stale_days
# -------------------------
# The number of days after which fixity check data will
# be recalulated. Defaults to 45 days. Used by some of the
# fixity scripts



# database
# ========
#
# There are three postgres databases used by DAITSS; this abbreviated
# example lists only the one for the silo-pool server and scripts.
#
# database:silo_db
# -----------------------
# Required, the database connection string for the silo-pool database.
# Supported vendors: postgres. Some fields are optional - for
# instance, if there is no password and you use the postgres default
# port, 5432:
#
#   postgres://username@hostname/database
#
# With port and password it looks like
#
#   vendor://username:password@hostname:port/database
#
#
# N.B.  Because we have a password in this config file, this file
# should have read permissions retricted to the user running the
# service, or an appropriately restricted group.


# silo-pools.example.org
# ======================
#
# This section sets the variables specific to the silo-pool web
# service.
#
# silo:log_database_queries
# -------------------------
# Should we log database queries? defaults to false.  These can
# generate very large logs, so it's only recommended for
# troubleshooting and learning.
#
# silo:log_filename
# -----------------
# If set, direct log information to this file. If neither log_filename
# nor log_syslog_facility are set, log to STDERR.  log_filename should
# be unique to this service.  If you want to share output from
# multiple services to one file, use syslog.
#
# silo:log_syslog_facility
# ------------------------
# If set, direct log information to this syslog facility (see
# /etc/syslog.conf). If neither log_filename nor log_syslog_facility
# are set, log to STDERR.
#
# silo:silo_temp_directory
# ------------------------
# A temporary directory for caching data from Tivoli
# data storage - only used with the FDA style of tape
# storage. Defaults to /var/tmp/
#
# silo:tivoli_server
# ------------------
# The name of the Tivolo tape server, if you are using
# DAITSS with the FDA style of tape storage. No defaults.


# disk-fixity
# ===========
#
# This section sets specific variables for the disk-fixity script.
# disk-fixity also uses database settings and the default
# fixity_stale_days and fixity_expired_days variables (several scripts
# use these latter).
#
# disk-fixity:fresh_enough
# ------------------------
# The number of days before which we will not repeat a fixity check.
# Defaults to zero (i.e., always perform a fixity check).
#
# disk-fixity:hostname
# --------------------
# The hostname we're checking: packages in the silo database
# are associated with a particular hostname.
#
# disk-fixity:log_syslog_facility
# -------------------------------
# If set, direct log information to this syslog facility (see
# /etc/syslog.conf). If neither log_filename nor log_syslog_facility
# are set, log to STDERR.
#
# disk-fixity:log_filename
# ------------------------
# If set, direct log information to this file. If neither log_filename
# nor log_syslog_facility are set, log to STDERR.  log_filename should
# be unique to this service.  If you want to share output from
# multiple services to one file, use syslog.
#
# disk-fixity:log_database_queries
# --------------------------------
# If set, log database queries. Can generate very large logs and
# degrade performance.
#
# disk-fixity:pid_directory
# -------------------------
# If pid_directory is set, use it to write a lock file (named
# disk-fixity.pid) so that there cannot be multiple copies of the
# script running. If not present no locking will be done.



# tape-fixity
# ===========
#
# This section sets specific variables for the tape-fixity script.
# tape-fixity also uses database settings and the default:fixity_stale_days
# variables (several scripts use these).
#
# tape-fixity:fixity_disk
# -----------------------
# The path to the scratch disk where we'll write copies of tape data
# to perform fixity checks. The FDA batches these up in 2-Terrabyte
# chunks. Note that all contents of this entire directory tree will be
# removed.
#
# tape-fixity:fresh_enough
# ------------------------
# The number of days before which we will not repeat a fixity check.
# Defaults to zero (will always perform a fixity check).
#
# tape-fixity:hostname
# --------------------
# The hostname we're checking: packages in the silo database
# are associated with a particular hostname.
#
# tape-fixity:log_syslog_facility
# -------------------------------
# If set, direct log information to this syslog facility (see
# /etc/syslog.conf). If neither log_filename nor log_syslog_facility
# are set, log to STDERR.
#
# tape-fixity:log_filename
# ------------------------
# If set, direct log information to this file. If neither log_filename
# nor log_syslog_facility are set, log to STDERR.  log_filename should
# be unique to this service.  If you want to share output from
# multiple services to one file, use syslog.
#
# tape-fixity:log_database_queries
# --------------------------------
# If set, log database queries. Can generate very large logs and
# degrade performance.
#
# tape-fixity:pid_directory
# -------------------------
# If pid_directory is set, use it to write a lock file (named
# tape-fixity.pid) so that there cannot be multiple copies of the
# script running. If not present no locking will be done
#
# tape-fixity:silo_user
# ---------------------
# The name of the user that's allowed to access the tape library.
# We use this to do an up-front sanity check to make sure we'll 
# be able to extract the tape data (otherwise, we'll fail to 
# find anything from the tivoli listing)
#
# tape-fixity:tivoli_server
# -------------------------
# The name of the Tivoli server that controls the tape library
# we're querying.

